= M07 - Desenvolupament web en entorn servidor
Cristòfol-Lluís Thwaite Rivas <crivasi@xtec.cat>

:doctype: book
:revdate: October 2025

:title-page:

:sectnums:
:sectnumlevels: 3
:toc:
:toclevels: 1

:sectnums!:
== Introducció

El desenvolupament web en entorn servidor ha evolucionat a un ritme trepidant en els últims vint-i-cinc anys.  En els seus principis, els desenvolupadors no només escrivien el codi que implementava la lògica de negoci de l'aplicació, sinó que també s'encarregaven de programar els components com l'autenticació d'usuaris, l'accés a les bases de dades i de més, permeten el bon funcionament de l'aplicació.  

Avui en dia, els programadors ens trobem amb un munt de _frameworks_ de desenvolupament d'aplicacions web i una miríada de components i llibreries de fàcil accés, que ens impulsen a un desenvolupament àgil i robust.

En aquest mòdul, aprendrem d'una manera introductoria com desenvolupar aplicacions web, centrant-nos en l'entorn de servidor. Utilitzarem PHP com a llenguatge de desenvolupament. La tria no és casual, PHP és un llenguatge madur i popular, que permet la creació d'aplicacions webs de fàcil manteniment, ràpides i fiables. 

A més a més, emprarem un _framework_ per aprendre a desenvolupar. Com s'ha mencionat anteriorment, els _frameworks_ ens proveeixen de molts dels components perquè un web funcioni correctament. També aporten convencions que redueixen la quantitat de codi que un desenvolupador ha de conèixer en un nou projecte. Si coneixes un concepte en un _framework_, aquest concepte el podràs traslladar a tots els projectes desenvolupats en ell. El _framework_ que farem servir és _Laravel_, el més utilitzat pel desenvolupament d'aplicacions web en projectes basats en PHP.

== Resultats d'aprenentatge

En finalitzar aquest mòdul l'alumne/a adquirirà els següents resultats d'aprenentatge:

*Introducció al desenvolupament en entorn servidor*

* RA1. Selecciona les arquitectures i tecnologies de programació web en entorn servidor, analitzant les seves capacitats i les característiques pròpies.

* RA2. Escriu sentències executables per un servidor web reconeixent i aplicant procediments d'integració del codi en llenguatge de marques.

*Lógica de programació i gestió de formularis*

* RA2. Escriu sentències executables per un servidor web reconeixent i aplicant procediments d'integració del codi en llenguatge de marques.

* RA3. Escriu blocs de sentències embeguts en llenguatges de marques, seleccionant i utilitzant les estructures de programació.

*Accés a dades i aunteticació*

* RA4. Desenvolupa aplicacions web embegudes en llenguatges de marques analitzant i incorporant funcionalitats segons especificacions.

* RA5. Desenvolupa aplicacions web identificant i aplicant mecanismes per separar el codi de presentació de la lògica de negoci.

* RA6. Desenvolupa aplicacions d’accés a magatzems de dades, aplicant mesures per mantenir la seguretat i la integritat de la informació.

*REST APIs i aplicacions web híbrides*

* RA7. Desenvolupa serveis web reutilitzables i accessibles mitjançant protocols web, verificant-ne el funcionament.

* RA8. Genera pàgines web dinàmiques analitzant i utilitzant tecnologies i frameworks del servidor web que afegeixin codi al llenguatge de marques.

* RA9. Desenvolupa aplicacions web híbrides seleccionant i utilitzant tecnologies, frameworks servidor i repositoris heterogenis d’informació.

// ----------------------
// Unitat 1
// ----------------------
:sectnums:
:sectnumoffset: 0
== Unitat 1. Introducció al desenvolupament en entorn servidor
:leveloffset: +1
include::unitat1.adoc[]
:leveloffset: -1


// ----------------------
// Unitat 2
// ----------------------
:sectnums:
:sectnumoffset: 0
== Unitat 2. Lògica de programació i gestió de formularis
:leveloffset: +1
include::unitat2.adoc[]
:leveloffset: -1

// ----------------------
// Unitat 3
// ----------------------
:sectnums:
:sectnumoffset: 0
== Unitat 3. Accés a dades i autenticació
:leveloffset: +1
include::unitat3.adoc[]
:leveloffset: -1

// ----------------------
// Unitat 4
// ----------------------
:sectnums:
:sectnumoffset: 0
== Unitat 4. REST APIs i aplicacions web híbrides
:leveloffset: +1
include::unitat4.adoc[]
:leveloffset: -1

